# Site settings
title: Adrian Statescu
email: mergesortv@gmail.com
description: "Application Security and Development"
baseurl: ""
url: "https://thinkphp.herokuapp.com"
twitter_username: thinkphp
github_username:  thinkphp
disqus_shortname: thinkphp

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

redcarpet:
    extensions: [ 'tables', 'autolink' ]

kramdown:
    input: GFM
    syntax_highlighter: rouge

    syntax_highlighter_opts:
        span:
            line_numbers: false
        block:
            line_numbers: true


links:
    - name:     About
      url:      https://thinkphp.herokuapp.com/about
      external: true
    - name:     GitHub
      url:      http://github.com/thinkphp
      external: true
    - name:     LinkedIn
      url:      http://linkedin.com/in/statescuadrian
      external: true

