# Site settings
title: Adrian Statescu
email: mergesortv@gmail.com
description: "A front-end developer JavaScript application, A back-end developer PHP application architecture and development, tooling, workflow and more."
baseurl: ""
url: "https://thinkphp.herokuapp.com"
twitter_username: thinkphp
github_username:  thinkphp
disqus_shortname: thinkphp
share: true

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
gems: ['kramdown']
exclude: ['config.ru', 'Gemfile', 'Gemfile.lock', 'vendor', 'Procfile', 'Rakefile']

redcarpet:
    extensions: [ 'tables', 'autolink' ]

kramdown:
    input: GFM
    syntax_highlighter: rouge

    syntax_highlighter_opts:
        span:
            line_numbers: false
        block:
            line_numbers: true


links:
    - name:     About
      url:      /about
    - name:     Projects
      url:      http://thinkphp.github.io
      external: true
    - name:     Contact
      url:      /contact

